# Generated by Django 3.1 on 2020-08-13 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0002_delete_crearusuarios'),
    ]

    operations = [
        migrations.CreateModel(
            name='Eventos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(max_length=128, verbose_name='event_name')),
                ('event_category', models.CharField(choices=[('1', 'Conferencia'), ('2', 'Seminario'), ('3', 'Congreso'), ('4', 'Curso')], max_length=16)),
                ('event_place', models.CharField(max_length=128, verbose_name='event_category')),
                ('event_address', models.CharField(max_length=128, verbose_name='event_category')),
                ('event_initial_date', models.DateTimeField()),
                ('event_final_date', models.DateTimeField()),
                ('event_type', models.CharField(choices=[('1', 'Virtual'), ('2', 'Presencial')], max_length=10)),
                ('thumbnail', models.ImageField(default='recipe_thumbnails/default.png', upload_to='recipe_thumbnails')),
            ],
        ),
    ]
