# Generated by Django 3.1 on 2020-08-13 05:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_eventos'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Eventos',
            new_name='CrearEventos',
        ),
    ]
