# Generated by Django 3.1 on 2020-08-13 05:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20200813_0049'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CrearEventos',
            new_name='CrearEvento',
        ),
    ]
