# Generated by Django 3.1 on 2020-08-13 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20200813_0108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crearevento',
            name='event_category',
            field=models.CharField(choices=[('1', 'Conferencia'), ('2', 'Seminario'), ('3', 'Congreso'), ('4', 'Curso')], max_length=16, verbose_name='Categoría del evento'),
        ),
        migrations.AlterField(
            model_name='crearevento',
            name='event_final_date',
            field=models.DateTimeField(verbose_name='Fecha final del evento'),
        ),
        migrations.AlterField(
            model_name='crearevento',
            name='event_initial_date',
            field=models.DateTimeField(verbose_name='Fecha inicial del evento'),
        ),
        migrations.AlterField(
            model_name='crearevento',
            name='event_type',
            field=models.CharField(choices=[('1', 'Virtual'), ('2', 'Presencial')], max_length=10, verbose_name='Modalidad del evento'),
        ),
    ]
