# Generated by Django 3.1 on 2020-08-13 06:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20200813_0120'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='crearevento',
            options={'ordering': ('-id',)},
        ),
    ]
