# Generated by Django 3.1 on 2020-08-13 23:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0008_auto_20200813_0123'),
    ]

    operations = [
        migrations.AddField(
            model_name='crearevento',
            name='event_user',
            field=models.ForeignKey(default=9, on_delete=django.db.models.deletion.CASCADE, to='auth.user'),
            preserve_default=False,
        ),
    ]
