# Generated by Django 3.1 on 2020-08-14 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_crearevento_event_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crearevento',
            name='event_category',
            field=models.CharField(choices=[('Conferencia', 'Conferencia'), ('Seminario', 'Seminario'), ('Congreso', 'Congreso'), ('Curso', 'Curso')], max_length=16, verbose_name='Categoría del evento'),
        ),
        migrations.AlterField(
            model_name='crearevento',
            name='event_type',
            field=models.CharField(choices=[('1', 'Virtual'), ('2', 'Presencial')], max_length=16, verbose_name='Modalidad del evento'),
        ),
    ]
